name: github pages

on:
  push:
    branches:
    - master
  schedule:
    # Always regenerate once every 4 hour
    - cron:  '15 */4 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Clone LLVM repo
      uses: actions/checkout@v2
      with:
        repository: llvm/llvm-project
        ref: 'master'
        path: 'llvm_src'

    - name: Build MLIR Dialect docs
      run: (mkdir llvm_src/build &&
            cd llvm_src/build &&
            cmake ../llvm -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_TARGETS_TO_BUILD="host" \
                          -DMLIR_INCLUDE_DOCS:BOOL=true -DLLVM_ENABLE_DOXYGEN:BOOL=true &&
            make -j$(nproc) mlir-doc doxygen-mlir)

    - name: Install MLIR Dialect docs
      run:  ./copy_docs.sh llvm_src/build/tools/mlir/docs/ website/content/docs/

    - name: Install MLIR Source docs
      run:  ./copy_docs.sh llvm_src/mlir/docs/ website/content/docs/

    - name: Install doxygen docs
      run:  cp -r llvm_src/build/tools/mlir/docs/doxygen/html website/static/doxygen

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # TODO: Revert back to version post next release.
        # extended: true

    - name: Build Website
      run: (cd website && hugo --minify -d ../public &&
            echo -n mlir.llvm.org > ../public/CNAME )

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
